name: tiktok_tutorial
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-190.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  firebase_storage: ^10.2.18
  cached_network_image: ^3.2.1
  get: ^4.6.5
  image_picker: ^0.8.5+3
  timeago: ^3.2.2
  video_compress: ^3.1.0
  video_player: ^2.4.5
  firebase_core: ^1.18.0
  google_sign_in: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

